# Generated by Django 6.0.3 on 2026-03-22 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'تصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المريض')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('medical_history', models.TextField(blank=True, verbose_name='السجل الطبي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'مرضى',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد المستحق')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'موردون',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200, verbose_name='الاسم التجاري')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم العلمي')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='الباركود')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='الشركة المصنعة')),
                ('form', models.CharField(choices=[('Tablet', 'أقراص'), ('Syrup', 'شراب'), ('Injection', 'حقن'), ('Cream', 'كريم/مرهم'), ('Drops', 'قطرة'), ('Capsule', 'كبسولات'), ('Inhaler', 'بخاخ'), ('Suppository', 'تحاميل'), ('Other', 'أخرى')], default='Tablet', max_length=50, verbose_name='الشكل الدوائي')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='الحد الأدنى للمخزون')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الوجبة (Batch)')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'أدوية',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الطبيب')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الوصفة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='تم الصرف')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'وصفة طبية',
                'verbose_name_plural': 'وصفات طبية',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('payment_method', models.CharField(choices=[('Cash', 'نقدي'), ('Card', 'بطاقة'), ('Credit', 'دين')], default='Cash', max_length=20, verbose_name='طريقة الدفع')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'عمليات المبيعات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المجموع الفرعي')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='الدواء')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المشتراة')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة الإجمالية')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الشراء')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='الدواء')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عملية شراء',
                'verbose_name_plural': 'عمليات المشتريات',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'مدير'), ('Pharmacist', 'صيدلي'), ('Cashier', 'كاشير')], default='Cashier', max_length=20, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
