# Generated by Django 6.0.3 on 2026-03-22 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='صيدليتي الذكية', max_length=200, verbose_name='اسم الصيدلية')),
                ('currency_unit', models.CharField(default='ج.م', max_length=20, verbose_name='الوحدة السعرية (العملة)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة (%)')),
                ('address', models.TextField(blank=True, verbose_name='عنوان الصيدلية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف الصيدلية')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug', verbose_name='الدواء')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'دواء في الوصفة',
                'verbose_name_plural': 'أدوية في الوصفات',
            },
        ),
    ]
